- name: Configure pound load balancer
  hosts: pound
  tasks:
    - name: Update the pound configuration file
      become: true
      template:
        src: templates/etc/pound.cfg.j2
        dest: /etc/pound.cfg
        owner: root
        group: root
        mode: 0644
      notify: "restart pound"

    - name: Ensure that pound is always running
      become: true
      service:
        name: pound
        state: started

  handlers:
    - name: Restarting pound load balancer
      listen: "restart pound"
      become: true
      service:
        name: pound
        state: restarted

- name: Configure apache backend servers
  hosts: apache
  tasks:
    - name: Update the httpd configuration file
      become: true
      template:
        src: templates/etc/httpd/conf/httpd.conf.j2
        dest: /etc/httpd/conf/httpd.conf
        owner: root
        group: root
        mode: 0644
      notify: "restart apache"

    - name: Ensure that apache is always running
      become: true
      service:
        name: httpd
        state: started

    - name: Configure httpd welcome page
      become: true
      template:
        src: templates/var/www/html/index.html.j2
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
      


  handlers:
    - name: Restarting apache
      listen: "restart apache"
      become: true
      service:
        name: httpd
        state: restarted
